' Copyright (c) 2017,  Met Office, on behalf of HMSO and Queen's Printer
' For further details please refer to the file LICENCE.original which you
' should have received as part of this distribution.

class global_mesh_map_mod::global_mesh_map_type {

  -global_mesh_map: integer[::]<<allocatable>>

  +<<create>>  global_mesh_map_constructor(<<in>>source_global_mesh_id:<<integer>>, <<in>>target_global_mesh_id:<<integer>>, <<in>>map:<<integer[:::]>> ) : global_mesh_map_type
  +<<destroy>> global_mesh_map_destructor()
  +clear()

  +get_source_id(): integer
  +get_target_id(): integer
  +get_nsource_cells(): integer
  +get_ntarget_cells_per_source_cell(): integer
  +get_ntarget_cells_per_source_x(): integer
  +get_ntarget_cells_per_source_y(): integer
  +get_cell_map( <<in>>cell_ids:<<integer[:]>>, <<out>>gid_map:<<integer[:::]>> )

}
