' Copyright (c) 2017,  Met Office, on behalf of HMSO and Queen's Printer
' For further details please refer to the file LICENCE.original which you
' should have received as part of this distribution.

class mesh_map_mod::mesh_map_type{

  -mesh_map: integer[::]<<allocatable>>

  +<<create>>  mesh_map_constructor( source_mesh_id:<<integer>>, target_mesh_id:<<integer>>, map:<<integer[:::]>> ) : mesh_map_type
  +<<destroy>> mesh_map_desctructor()
  +clear()

  +get_source_id(): integer
  +get_target_id(): integer
  +get_nsource_cells(): integer
  +get_ntarget_cells_per_source_cell(): integer
  +get_ntarget_cells_per_source_x(): integer
  +get_ntarget_cells_per_source_y(): integer
  +get_map_from_cell(<<in>>source_lid:integer, <<out>>map:integer[:] )
  +get_cell_map(<<in>>source_lid:integer): integer[::],pointer
  +get_whole_cell_map(): integer[:::],pointer
}


