' Copyright (c) 2017,  Met Office, on behalf of HMSO and Queen's Printer
' For further details please refer to the file LICENCE.original which you
' should have received as part of this distribution.

class partition_mod::partition_type {
  -global_cell_id: integer[] <<allocatable>>
  -num_inner: integer[] <<allocatable>>
  -last_inner_cell: integer[] <<allocatable>>
  -inner_depth: integer
  -num_edge: integer
  -last_edge_cell: integer
  -num_halo: integer[] <<allocatable>>
  -last_halo_cell: integer <<allocatable>>
  -halo_depth: integer
  -num_ghost: integer
  -global_num_cells: integer
  -npanels: integer

  +<<create>>  partition_constructor(<<in>>global_mesh: global_mesh_type, <<in>>partitioner: partitioner_interface<<pointer>>, <<in>>xproc: integer, <<in>>yproc: integer, <<in>>max_stencil_depth: integer, <<in>>local_rank: integer, <<in>>total_ranks: integer )
  +<<create>>  partition_constructor_unit_test_data()
  +<<destroy>> partition_destructor()
  +<<operator =>> partition_type_assign(<<out>>dest: partition, <<in>>source: partition )

  +get_halo_depth() : integer
  +get_inner_depth() : integer
  +get_last_edge_cell() : integer
  +get_last_halo_cell() : integer
  +get_last_inner_cell( <<in>>depth: integer ) : integer
  +get_num_cells_edge() : integer
  +get_num_cells_ghost() : integer
  +get_num_panels_global_mesh() : integer
  +get_num_cells_halo( <<in>>depth: integer ) : integer
  +get_num_cells_in_layer() : integer
  +get_num_cells_inner( <<in>>depth: integer ) : integer
}
