' Copyright (c) 2020,  Met Office, on behalf of HMSO and Queen's Printer
' For further details please refer to the file LICENCE.original which you
' should have received as part of this distribution.

class fieldspec_xml_parser_mod::fieldspec_xml_parser_mod <<Module>>{
  -fieldspec_collection : fieldspec_collection_type
  -fieldspec_factory : fieldspec_factory_type
  -fieldspec_factory_initialised : logical
  -ignore_element : logical
  -in_field_def : logical
  -in_field_group : logical
  -in_field : logical
  -in_field_variable : logical
  -xml_field_variable : character

  +populate_fieldspec_collection( <<in>> iodef_filepath : character )
  -switch_xml_element_flag( <<in>> element_name : character, <<in>> new_value : logical )
  -startElement_handler( <<in>> namespaceURI : character, <<in>> localname : character, <<in>> name : character, <<in>> attributes : dictionary_t )
  -text_handler( <<in>> text : character )
  -endElement_handler( <<in>> namespaceURI : character, <<in>> localname : character, <<in>> name : character )
}
