' Copyright (c) 2020,  Met Office, on behalf of HMSO and Queen's Printer
' For further details please refer to the file LICENCE.original which you
' should have received as part of this distribution.

class fieldspec_collection_mod::fieldspec_collection_type <<Singleton>> {
  -fieldspec_list : linked_list_type

  <<create>>-fieldspec_collection_constructor() : fieldspec_collection_type <<pointer>>
  <<destroy>>+fieldspec_collection_destructor()
  +check_unique_id_in_use( <<in>> unique_id : character ) : logical
  +generate_and_add_fieldspec( <<in>> unique_id: character, <<in>> mesh_id : integer, <<in>> domain : integer, <<in>> order : integer, <<in>> field_kind : integer, <<in>> field_type : integer, <<in>> io_driver : integer, )
  +add_fieldspec( <<in>> fieldspec : fieldspec_type )
  +get_fieldspec( <<in>> unique_id : character ) : fieldspec_type <<pointer>>
  +get_length() : integer
  +clear()
}
