' Copyright (c) 2020,  Met Office, on behalf of HMSO and Queen's Printer
' For further details please refer to the file LICENCE.original which you
' should have received as part of this distribution.

class fieldspec_mod::fieldspec_type {
  -unique_id : character
  -mesh_id : integer
  -domain : integer
  -order : integer
  -field_kind : integer
  -field_type : integer
  -io_driver : integer

  <<create>>-fieldspec_constructor( <<in>> unique_id, <<in>> mesh_id : integer, <<in>> domain : integer, <<in>> order : integer, <<in>> field_kind : integer, <<in>> field_type : integer, <<in>> io_driver : integer) : fieldspec_type
  +get_unique_id() : character
  +get_mesh_id() : integer
  +get_domain() : integer
  +get_order() : integer
  +get_kind() : integer
  +get_type() : integer
  +get_io_driver() : integer
}
