' Copyright (c) 2020,  Met Office, on behalf of HMSO and Queen's Printer
' For further details please refer to the file LICENCE.original which you
' should have received as part of this distribution.

@startuml

!include look.iuml
!include fieldspec_mod.iuml
!include fieldspec_collection_mod.iuml
!include fieldspec_xml_parser_mod.iuml
!include fieldspec_factory_mod.iuml

fieldspec_collection_mod::fieldspec_collection_type o-> "*" fieldspec_mod::fieldspec_type
linked_list_data_mod::linked_list_data_type ^-- fieldspec_mod::fieldspec_type
fieldspec_xml_parser_mod::fieldspec_xml_parser_mod *-- fieldspec_factory_mod::fieldspec_factory_type
fieldspec_xml_parser_mod::fieldspec_xml_parser_mod *-- fieldspec_collection_mod::fieldspec_collection_type
@enduml
