' Copyright (c) 2020,  Met Office, on behalf of HMSO and Queen's Printer
' For further details please refer to the file LICENCE.original which you
' should have received as part of this distribution.

class fieldspec_factory_mod::fieldspec_factory_type {
  -unique_id : character
  -mesh_id : integer
  -domain : integer
  -order : integer
  -field_kind : integer
  -field_type : integer
  -io_driver : integer

  <<create>>-fieldspec_factory_constructor() : fieldspec_factory_type
  +initialise()
  +finalise() : fieldspec_type
  +set_unique_id( <<in>> unique_id : character )
  +set_mesh_id( <<in>> mesh_id : integer )
  +set_domain( <<in>> domain : integer )
  +set_order( <<in>> order : integer )
  +set_kind( <<in>> field_kind : integer )
  +set_type( <<in>> field_type : integer )
  +set_io_driver( <<in>> io_driver : integer )
}
