!-----------------------------------------------------------------------------
! (C) Crown copyright 2021 Met Office. All rights reserved.
! The file LICENCE, distributed with this code, contains details of the terms
! under which the code may be used.
!-----------------------------------------------------------------------------
!> @brief Temporary module to contain various enumerated types for use
!!        in the new transport scheme. These should be replaced by ones
!!        generated by the namelists.

module transport_enumerated_types_mod

  use constants_mod, only: i_def

  implicit none

  integer(kind=i_def), parameter :: equation_conservative = 421_i_def
  integer(kind=i_def), parameter :: equation_advective    = 311_i_def
  integer(kind=i_def), parameter :: equation_consistent   = 919_i_def

  integer(kind=i_def), parameter :: splitting_none       = 1_i_def
  integer(kind=i_def), parameter :: splitting_strang_vhv = 2_i_def
  integer(kind=i_def), parameter :: splitting_strang_hvh = 3_i_def
  integer(kind=i_def), parameter :: splitting_vh         = 4_i_def
  integer(kind=i_def), parameter :: splitting_hv         = 5_i_def

  integer(kind=i_def), parameter :: scheme_mol_3d  = 1_i_def
  integer(kind=i_def), parameter :: scheme_ffsl_3d = 2_i_def
  integer(kind=i_def), parameter :: scheme_split   = 3_i_def

  integer(kind=i_def), parameter :: split_method_null = 0_i_def
  integer(kind=i_def), parameter :: split_method_mol = 1_i_def
  integer(kind=i_def), parameter :: split_method_ffsl = 2_i_def
  integer(kind=i_def), parameter :: split_method_sl   = 3_i_def

  integer(kind=i_def), parameter :: direction_3d = 419843_i_def
  integer(kind=i_def), parameter :: direction_h  = 6423_i_def
  integer(kind=i_def), parameter :: direction_v  = 1483_i_def

  integer(kind=i_def), parameter :: monotone_none     = 1_i_def
  integer(kind=i_def), parameter :: monotone_clipping = 2_i_def
  integer(kind=i_def), parameter :: monotone_koren    = 3_i_def

contains

end module transport_enumerated_types_mod
