'!-----------------------------------------------------------------------------
'! (C) Crown copyright 2021 Met Office. All rights reserved.
'! The file LICENCE, distributed with this code, contains details of the terms
'! under which the code may be used.
'!-----------------------------------------------------------------------------

class gen_lbc_mod::gen_lbc_type {

  -mesh_name: string
  -geometry:  integer
  -topology:  integer
  -coord_sys: integer
  -coord_units_x: string
  -coord_units_y: string
  -constructor_inputs: string
  -outer_cells_x: integer
  -outer_cells_y: integer
  -nmaps: integer

  -n_nodes: integer
  -n_edges: integer
  -n_faces: integer

  -rim_depth: integer

  -target_mesh_names: string[:] <<allocatable>>

  -global_mesh_maps: global_mesh_map_collection_type <<allocatable>>

  -cell_next: integer[::] <<allocatable>>
  -nodes_on_cell: integer[::] <<allocatable>>
  -nodes_on_edge: integer[::] <<allocatable>>
  -edges_on_cell: integer[::] <<allocatable>>

  -node_coords: real[::] <<allocatable>>
  -cell_coords: real[::] <<allocatable>>

  -nodes_per_face: integer
  -edges_per_face: integer
  -nodes_per_edge: integer

  -max_num_faces_per_node: integer

  -lam_strategy: gen_planar_type
  -base_h_panel: base_lbc_panel_type
  -base_v_panel: base_lbc_panel_type

  -north_pole: real[2]
  -null_island: real[2]

  +<<create>>gen_lbc_constructor( <<in>> lam_strategy:gen_planar_type, <<in>> rim_depth: integer ): gen_lbc_type

  +generate( ... )
  +get_metadata( ... )
  +get_dimensions( ... )
  +get_coordinates( ... )
  +get_connectivity( ... )
  +get_global_mesh_maps( ... )

  +write_mesh()
  +clear()
}

class gen_lbc_mod::base_lbc_panel_type {

  -length  : integer[:]
  -depth   : integer[:]
  -n_cells : integer[:]
  -n_edges : integer[:]
  -n_nodes : integer[:]

  -edges_per_face : integer[:]
  -nodes_per_face : integer[:]

  -cell_next   : integer[::] <<allocatable>>
  -north_cells : integer[:]  <<allocatable>>
  -south_cells : integer[:]  <<allocatable>>
  -east_cells  : integer[:]  <<allocatable>>
  -west_cells  : integer[:]  <<allocatable>>

  +<<create>>base_lbc_panel_constructor( <<in>> panel_length:integer, <<in>> panel_depth:integer ): base_lbc_panel_type

  +clear()
}

gen_lbc_mod::gen_lbc_type -|> ugrid_generator_mod::ugrid_generator_type
gen_lbc_mod::gen_lbc_type o-> "2" gen_lbc_mod::base_lbc_panel_type
