' (c) Crown copyright 2021 Met Office. All rights reserved.
' The file LICENCE, distributed with this code, contains details of the terms
' under which the code may be used.

interface io_context_type {
  +get_clock() : clock_type
}
