' Copyright (c) 2017,  Met Office, on behalf of HMSO and Queen's Printer
' For further details please refer to the file LICENCE.original which you
' should have received as part of this distribution.

@startuml

!include look.iuml
!include field/field_mod.iuml
!include field/field_parent_mod.iuml
!include field/pure_abstract_field_mod.iuml
!include field/function_space_mod.iuml
!include field/function_space_collection_mod.iuml
!include field/field_collection_mod.iuml
!include field/field_collection_iterator_mod.iuml

field_collection_mod::field_collection_type o-> "*" field_mod::field_type
field_collection_mod::field_collection_type ---  field_collection_iterator_mod::field_collection_iterator_type
field_collection_mod::field_collection_type ---  field_collection_iterator_mod::field_collection_real_iterator_type
field_parent_mod::field_parent_type ^- field_mod::field_type
field_parent_mod::field_parent_proxy_type ^- field_mod::field_proxy_type
field_mod::field_type o---> function_space_mod::function_space_type
pure_abstract_field_mod::pure_abstract_field_type ^-- field_mod::field_pointer_type
field_mod::field_type <--o field_mod::field_pointer_type
pure_abstract_field_mod::pure_abstract_field_type ^-- field_parent_mod::field_parent_type
linked_list_data_mod::linked_list_data_type ^-- pure_abstract_field_mod::pure_abstract_field_type

@enduml
