' Copyright (c) 2017,  Met Office, on behalf of HMSO and Queen's Printer
' For further details please refer to the file LICENCE.original which you
' should have received as part of this distribution.

@startuml

!include look.iuml
!include mesh/function_space_chain_mod.iuml
!include mesh/function_space_pointer_mod.iuml

linked_list_mod::linked_list_type o-> "*" linked_list_data_mod::linked_list_data_type


@enduml
