' Copyright (c) 2017,  Met Office, on behalf of HMSO and Queen's Printer
' For further details please refer to the file LICENCE.original which you
' should have received as part of this distribution.

@startuml

!include look.iuml
!include solver/iterative_solver_mod.iuml
!include solver/linear_operator_mod.iuml
!include solver/preconditioner_mod.iuml
!include solver/cg_mod.iuml
!include solver/bicgstab_mod.iuml
!include solver/hierarchical_linear_operator_mod.iuml
!include solver/hierarchical_preconditioner_mod.iuml
@enduml
