'!-----------------------------------------------------------------------------
'! (C) Crown copyright 2021 Met Office. All rights reserved.
'! The file LICENCE, distributed with this code, contains details of the terms
'! under which the code may be used.
'!-----------------------------------------------------------------------------

abstract class hierarchical_linear_operator_mod::abstract_hierarchical_linear_operator_type{
    {abstract}+coarsen(<<in>>self:abstract_hierarchical_linear_operator_type, <<in>>fs_coarse, <<inout>>coarse_operator) 
}

linear_operator_mod::abstract_linear_operator_type ^- hierarchical_linear_operator_mod::abstract_hierarchical_linear_operator_type