' (c) Crown copyright 2020 Met Office. All rights reserved.
' The file LICENCE, distributed with this code, contains details of the terms
' under which the code may be used.

@startuml

!include look.iuml
!include clock_mod.iuml
!include context_mod.iuml
!include time_axis_mod.iuml

@enduml
