' (C) Crown copyright 2017 Met Office. All rights reserved.
' For further details please refer to the file LICENCE which you should have
' received as part of this distribution.

class quadrature_xyz_mod::quadrature_xyz_type {

  -np_xyz: integer
  -weights_xyz: real[:]  <<allocatable>>
  -points_xyz : real[::] <<allocatable>>

  +<<create>>init_quadrature_variable( <<in>>np_x: integer, <<in>>np_y: integer, <<in>>np_z: integer, <<in>>rule: quadrature_rule ) : quadrature_xyz_type
  +<<create>>init_quadrature_symmetrical( <<in>>np: integer, <<in>>rule: quadrature_rule ) : quadrature_xyz_type
  +compute_function( <<in>>function_to_call: integer, <<in>> function_space: function_space_type, <<in>>fspace_dim: integer, <<in>>ndf: integer, <<out>>basis: real[:::] )
  +get_quadrature_proxy() : quadrature_xyz_proxy_type
  +quadrature_final()
  +<<destroy>>quadrature_destructor()

}

class quadrature_xyz_mod::quadrature_xyz_proxy_type {
  +np_xyz: integer 
  +weights_xyz: real[:]  <<pointer>>
  +points_xyz : real[::] <<pointer>>
}

quadrature_mod::quadrature_type <|-- quadrature_xyz_mod::quadrature_xyz_type
quadrature_xyz_mod::quadrature_xyz_proxy_type -> quadrature_xyz_mod::quadrature_xyz_type
