' (c) Crown copyright 2018 Met Office. All rights reserved.
' The file LICENCE, distributed with this code, contains details of the terms
' under which the code may be used.

class field_collection_mod::field_collection_type {
  -field_list: linked_list_type
  -name: string

  +initialise(<<in optional>> name : string ) :
  +copy_collection( <<out>>dest : field_collection_type, <<in optional>> name : string )
  +add_field( <<in>>field: field_type ) :
  +add_reference_to_field( <<in>>field: field_type <<pointer>> ) :
  +remove_field( <<in>>field_name: string ) :
  +field_exists( <<in>>field_name: string ) :
  +get_first_item() : linked_list_item_type
  +get_field( <<in>>field_name: string ) : <<pointer>> field_type
  +get_integer_field( <<in>>field_name: string ) : <<pointer>> integer_field_type
  +get_r_solver_field( <<in>>field_name: string ) : <<pointer>> r_solver_field_type
  +get_r_tran_field( <<in>>field_name: string ) : <<pointer>> r_tran_field_type
  +get_length() : integer
  +get_name() : string
  +clear() :
  <<destroy>>+field_collection_destructor()
}
