' (c) Crown copyright 2019 Met Office. All rights reserved.
' The file LICENCE, distributed with this code, contains details of the terms
' under which the code may be used.

class halo_routing_collection_mod::halo_routing_collection_type {

  -halo_routing_list: linked_list_type <<payload_type=halo_routing_type>>

  +<<create>>  halo_routing_collection_constructor() : halo_routing_collection_type
  +<<destroy>> halo_routing_collection_destructor()
  +clear()
  +get_halo_routing(<<in>>mesh_id: integer, <<in>>element_order: integer, <<in>>lfric_fs: integer, <<in>>ndata: integer, <<in>>fortran_type: integer, <<in>>fortran_kind: integer) : <<pointer>> halo_routing_type
}


