' Copyright (c) 2017,  Met Office, on behalf of HMSO and Queen's Printer
' For further details please refer to the file LICENCE.original which you
' should have received as part of this distribution.

abstract class operator_parent_mod::operator_parent_type{
  -fs_from       : function_space_type <<pointer>>
  -fs_to         : function_space_type <<pointer>>
  +operator_parent_initialiser( <<in>>fs_to: function_space_type, <<in>>fs_from: function_space_type )
  +operator_parent_proxy_initialiser( <<inout>>operator_proxy: operator_parent_proxy_type )
  +copy_operator_parent(<<in>>dest: operator_parent_type )
  +get_fs_from():function_space_type
  +get_fs_to():function_space_type
  +which_fs_from():integer
  +which_fs_to():integer
  +get_mesh():mesh_mod::mesh_type
  <<destroy>>+destroy_operator_parent()
}

abstract class operator_parent_mod::operator_parent_proxy_type{
  +fs_from       : function_space_type <<pointer>>
  +fs_to         : function_space_type <<pointer>>
  <<destroy>>+destroy_operator_parent_proxy()
}

class operator_r64_mod::operator_r64_type {
  -local_stencil : real[:::] <<allocatable>>
  +initialise( <<in>>fs_to: function_space_type, <<in>>fs_from: function_space_type ) : operator_r64_type
  +get_proxy()     : operator_r64_proxy_type
  +deep_copy() : operator_r64_type
  +is_initialised() : logical
  <<destroy>>+operator_r64_destructor()
}

class operator_r64_mod::operator_r64_proxy_type {
  +local_stencil : real[:::] <<pointer>>
  +ncell_3d      : integer
  <<destroy>>+operator_r64_proxy_destructor()
}

class columnwise_operator_mod::columnwise_operator_type {
  __ private data __
  .. scalars ..
  -alpha   : integer
  -beta    : integer
  -gamma_m : integer
  -gamma_p : integer
  -bandwidth : integer
  -nrow : integer
  -ncol : integer
  -ndof_face_to : integer
  -ndof_face_from : integer
  -ndof_interior_to : integer
  -ndof_interior_from : integer
  -ndof_cell_to : integer
  -ndof_cell_from : integer
  -ncell_2d : integer
  .. integer maps ..
  -column_dofmap_to: integer[::] <<allocatable>>
  -column_dofmap_from: integer[::] <<allocatable>>
  -column_banded_dofmap_to: integer[::] <<allocatable>>
  -column_banded_dofmap_from: integer[::] <<allocatable>>
  -indirection_dofmap_to: integer[:] <<allocatable>>
  -indirection_dofmap_from: integer[:] <<allocatable>>
  .. real data ..
  -columnwise_matrix : real[:::] <<allocatable>>
 == contains ==
  -- private procedures --
  -allocate_memory()
  <<nopass>>-get_gcd()
  -build_dofmaps()
  -extract_mesh_fs_info()
  -- public procedures --
  <<create>>+columnwise_operator_constructor()
  <<destroy>>+columnwise_operator_destructor()
  +get_proxy()
  +get_alpha()
  +get_beta()
  +get_gamma_m()
  +get_gamma_p()
  +columnwise_operator_product()
  +columnwise_operator_sum()
}

class columnwise_operator_mod::columnwise_operator_proxy_type {
  +fs_from       : function_space_type <<pointer>>
  +fs_to         : function_space_type <<pointer>>
  +alpha   : integer
  +beta    : integer
  +gamma_m : integer
  +gamma_p : integer
  +bandwidth : integer
  +nrow : integer
  +ncol : integer
  +ncell_2d : integer
  +columnwise_matrix[:::] : real <<pointer>>
  +column_banded_dofmap_to[::] : integer <<pointer>>
  +column_banded_dofmap_from[::] : integer <<pointer>>
  +indirection_dofmap_to[:] : integer <<pointer>>
  +indirection_dofmap_from[:] : integer <<pointer>>
}

operator_r64_mod::operator_r64_type --|> operator_parent_mod::operator_parent_type
columnwise_operator_mod::columnwise_operator_type --|> operator_parent_mod::operator_parent_type
operator_r64_mod::operator_r64_proxy_type --|> operator_parent_mod::operator_parent_proxy_type
columnwise_operator_mod::columnwise_operator_proxy_type --|> operator_parent_mod::operator_parent_proxy_type
