' (c) Crown copyright 2018 Met Office. All rights reserved.
' The file LICENCE, distributed with this code, contains details of the terms
' under which the code may be used.

class quadrature_rule_gauss_lobatto_mod::quadrature_rule_gauss_lobatto_type {
  quadrature_rule( <<in>>nqp_1d: integer) : real(::)
}

quadrature_rule_mod::quadrature_rule_type <|-- quadrature_rule_gauss_lobatto_mod::quadrature_rule_gauss_lobatto_type
