' (c) Crown copyright 2020 Met Office. All rights reserved.
' The file LICENCE, distributed with this code, contains details of the terms
' under which the code may be used.

class stencil_dofmap_mod::stencil_dofmap_type {
  -dofmap_shape : integer
  -dofmap_size : integer
  -dofmap : integer[:::] <<allocatable>>
  -local_size : integer[] <<allocatable>>

  <<create>>stencil_dofmap_constructor( <<in>>st_shape : integer, <<in>>st_depth : integer, <<in>>ndf : integer, <<in>>mesh <<pointer>> : mesh_type, <<in>>master_dofmap : master_dofmap_type  ) : stencil_dofmap_type

  +get_dofmap(<<in>>cell : integer) : integer[::] <<pointer>>
  +get_whole_dofmap() : integer[:::] <<pointer>>
  +get_size() : integer
  +get_local_size() : integer
  +get_stencil_sizes() : integer[] <<pointer>>
  +clear()
  <<destroy>>stencil_dofmap_destructor()
}
