' Copyright (c) 2017,  Met Office, on behalf of HMSO and Queen's Printer
' For further details please refer to the file LICENCE.original which you
' should have received as part of this distribution.

abstract class linked_list_data_mod::linked_list_data_type {
  -id: integer

  +get_id() : integer
  +set_id( <<in>>id : integer )
}
