' (c) Crown copyright 2021 Met Office. All rights reserved.
' The file LICENCE, distributed with this code, contains details of the terms
' under which the code may be used.

class model_clock_type {
  -first_step: Integer
  -current_step: Integer
  -last_step: Integer
  -seconds_per_step: Float
  -initialisation_phase: Boolean
  -starting: Boolean
  -calendar: calendar_type <<allocatable>>
  -last_spinup_step: Integer
  -spinup_fraction: Float

  +initialise(calendar: calendar_type, first: String, last: String, seconds_per_step: Float, spinup_period: Float)
  +tick(): Boolean
  +get_first_step(): Integer
  +get_step(): Integer
  +get_last_step(): Integer
  +get_seconds_per_step(): Float
  +seconds_from_step(period: Integer): Float
  +is_initialisation(): Boolean
  +is_running(): Boolean
  +get_calendar(): <<pointer>>calendar_type
  +get_spinup_fraction(): Float
  +is_spinning_up(): Boolean
  -calculate_spinup_fraction(): Float
}
clock_type ^- model_clock_type
